import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getSocketPath } from "./server.js";

const SETTINGS_KEY = "agentdeck-managed";

interface HookConfig {
  matcher: string;
  hooks: { type: "command"; command: string; async?: boolean }[];
}

interface SettingsHooks {
  PreToolUse?: HookConfig[];
  PostToolUse?: HookConfig[];
  SubagentStart?: HookConfig[];
  SubagentStop?: HookConfig[];
  Stop?: HookConfig[];
}

interface Settings {
  hooks?: SettingsHooks;
  [key: string]: unknown;
}

export async function ensureHookScript(rootPath: string): Promise<string> {
  const dir = path.join(rootPath, ".claude", "hooks");
  await fs.mkdir(dir, { recursive: true });
  const script = path.join(dir, "agentdeck-emit.sh");
  const socket = getSocketPath();
  const content = `#!/bin/bash
# Generated by AgentDeck. Forwards Claude Code hook payloads to the AgentDeck app.
HOOK_JSON=$(cat)
EVENT_NAME="$1"
SOCKET="${socket}"
DEBUG_LOG="$HOME/.agentdeck-hooks.log"

printf '[%s] %s %s\\n' "$(date -u +%H:%M:%S)" "$EVENT_NAME" "$HOOK_JSON" >> "$DEBUG_LOG"

# Build a single JSON line. We rely on jq if available, fall back to envelope.
if command -v jq >/dev/null 2>&1; then
  PAYLOAD=$(printf '%s' "$HOOK_JSON" | jq -c \\
    --arg type "$EVENT_NAME" \\
    --arg ts "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ 2>/dev/null || date -u +%Y-%m-%dT%H:%M:%SZ)" \\
    --arg cwd "$PWD" \\
    '{
       type: $type,
       timestamp: $ts,
       sessionId: (.session_id // ""),
       agentId: (.agent_id // null),
       agentName: (.agent_name // .subagent_name // null),
       agentTranscriptPath: (.agent_transcript_path // null),
       transcriptPath: (.transcript_path // null),
       toolName: (.tool_name // null),
       toolInput: (.tool_input // {}),
       success: (.success // null),
       reason: (.reason // null),
       cwd: $cwd
     }')
else
  PAYLOAD=$(printf '{"type":"%s","raw":%s}' "$EVENT_NAME" "$HOOK_JSON")
fi

# Best-effort write; never block Claude Code.
if command -v nc >/dev/null 2>&1; then
  printf '%s\\n' "$PAYLOAD" | nc -U -w 1 "$SOCKET" >/dev/null 2>&1 || true
fi

exit 0
`;
  await fs.writeFile(script, content, "utf8");
  await fs.chmod(script, 0o755);
  return script;
}

export async function installHooks(rootPath: string): Promise<void> {
  const script = await ensureHookScript(rootPath);
  const settingsPath = path.join(rootPath, ".claude", "settings.json");
  let settings: Settings = {};
  try {
    const raw = await fs.readFile(settingsPath, "utf8");
    settings = JSON.parse(raw) as Settings;
  } catch {
    settings = {};
  }
  settings.hooks = settings.hooks ?? {};

  const events: (keyof SettingsHooks)[] = [
    "PreToolUse",
    "PostToolUse",
    "SubagentStart",
    "SubagentStop",
    "Stop",
  ];
  for (const event of events) {
    const cmd = `bash ${script} ${event}`;
    const list = settings.hooks[event] ?? [];
    const already = list.some((h) =>
      h.hooks.some((x) => x.command === cmd),
    );
    if (already) continue;
    list.push({
      matcher: "*",
      hooks: [{ type: "command", command: cmd, async: true }],
    });
    settings.hooks[event] = list;
  }
  // Add a marker so we can detect/remove our own entries later.
  settings[SETTINGS_KEY] = true;
  await fs.writeFile(
    settingsPath,
    JSON.stringify(settings, null, 2) + "\n",
    "utf8",
  );
}

export async function isHooksInstalled(rootPath: string): Promise<boolean> {
  const settingsPath = path.join(rootPath, ".claude", "settings.json");
  try {
    const raw = await fs.readFile(settingsPath, "utf8");
    const settings = JSON.parse(raw) as Settings;
    return settings[SETTINGS_KEY] === true;
  } catch {
    return false;
  }
}
