import { promises as fs } from "node:fs";
import path from "node:path";
import { getSocketPath } from "./server";

const SETTINGS_KEY = "agent-board-managed";
const isWindows = process.platform === "win32";

interface HookConfig {
  matcher: string;
  hooks: { type: "command"; command: string; async?: boolean }[];
}

interface SettingsHooks {
  PreToolUse?: HookConfig[];
  PostToolUse?: HookConfig[];
  SubagentStart?: HookConfig[];
  SubagentStop?: HookConfig[];
  Stop?: HookConfig[];
}

interface Settings {
  hooks?: SettingsHooks;
  [key: string]: unknown;
}

function bashScript(socket: string): string {
  return `#!/bin/bash
# Generated by AgentBoard. Forwards Claude Code hook payloads to the AgentBoard app.
HOOK_JSON=$(cat)
EVENT_NAME="$1"
SOCKET="${socket}"

if command -v jq >/dev/null 2>&1; then
  PAYLOAD=$(printf '%s' "$HOOK_JSON" | jq -c \\
    --arg type "$EVENT_NAME" \\
    --arg ts "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ 2>/dev/null || date -u +%Y-%m-%dT%H:%M:%SZ)" \\
    --arg cwd "$PWD" \\
    '{
       type: $type,
       timestamp: $ts,
       sessionId: (.session_id // ""),
       agentId: (.agent_id // null),
       agentName: (.agent_name // .subagent_name // null),
       agentTranscriptPath: (.agent_transcript_path // null),
       transcriptPath: (.transcript_path // null),
       toolName: (.tool_name // null),
       toolInput: (.tool_input // {}),
       success: (.success // null),
       reason: (.reason // null),
       lastAssistantMessage: (.last_assistant_message // null),
       cwd: $cwd
     }')
else
  PAYLOAD=$(printf '{"type":"%s","raw":%s}' "$EVENT_NAME" "$HOOK_JSON")
fi

if command -v nc >/dev/null 2>&1; then
  printf '%s\\n' "$PAYLOAD" | nc -U -w 1 "$SOCKET" >/dev/null 2>&1 || true
fi

exit 0
`;
}

function powershellScript(pipe: string): string {
  return `# Generated by AgentBoard. Forwards Claude Code hook payloads to the AgentBoard app.
param([string]$EventName)

$ErrorActionPreference = 'SilentlyContinue'
$hookJson = [Console]::In.ReadToEnd()

try {
  $parsed = $hookJson | ConvertFrom-Json
} catch {
  $parsed = $null
}

$payload = [ordered]@{
  type = $EventName
  timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ")
  sessionId = if ($parsed.session_id) { $parsed.session_id } else { "" }
  agentId = $parsed.agent_id
  agentName = if ($parsed.agent_name) { $parsed.agent_name } elseif ($parsed.subagent_name) { $parsed.subagent_name } else { $null }
  agentTranscriptPath = $parsed.agent_transcript_path
  transcriptPath = $parsed.transcript_path
  toolName = $parsed.tool_name
  toolInput = if ($parsed.tool_input) { $parsed.tool_input } else { @{} }
  success = $parsed.success
  reason = $parsed.reason
  lastAssistantMessage = $parsed.last_assistant_message
  cwd = (Get-Location).Path
}

$line = ($payload | ConvertTo-Json -Compress -Depth 10)

# Connect to named pipe and send a single line. Best-effort.
$pipeName = "${pipe}"
try {
  $client = New-Object System.IO.Pipes.NamedPipeClientStream(".", $pipeName, [System.IO.Pipes.PipeDirection]::Out)
  $client.Connect(1000)
  $writer = New-Object System.IO.StreamWriter($client)
  $writer.WriteLine($line)
  $writer.Flush()
  $writer.Dispose()
  $client.Dispose()
} catch {
  # silently ignore; never block Claude Code
}

exit 0
`;
}

export async function ensureHookScript(rootPath: string): Promise<string> {
  const dir = path.join(rootPath, ".claude", "hooks");
  await fs.mkdir(dir, { recursive: true });
  const transport = getSocketPath();

  if (isWindows) {
    // On Windows, getSocketPath returns the pipe name (without the \\.\pipe\ prefix).
    const script = path.join(dir, "agent-board-emit.ps1");
    await fs.writeFile(script, powershellScript(transport), "utf8");
    return script;
  }

  const script = path.join(dir, "agent-board-emit.sh");
  await fs.writeFile(script, bashScript(transport), "utf8");
  await fs.chmod(script, 0o755);
  return script;
}

function commandFor(scriptPath: string, event: string): string {
  if (isWindows) {
    return `pwsh -NoProfile -ExecutionPolicy Bypass -File "${scriptPath}" ${event}`;
  }
  return `bash "${scriptPath}" ${event}`;
}

export async function installHooks(rootPath: string): Promise<void> {
  const script = await ensureHookScript(rootPath);
  const settingsPath = path.join(rootPath, ".claude", "settings.json");
  let settings: Settings = {};
  try {
    const raw = await fs.readFile(settingsPath, "utf8");
    settings = JSON.parse(raw) as Settings;
  } catch {
    settings = {};
  }
  settings.hooks = settings.hooks ?? {};

  const events: (keyof SettingsHooks)[] = [
    "PreToolUse",
    "PostToolUse",
    "SubagentStart",
    "SubagentStop",
    "Stop",
  ];
  for (const event of events) {
    const cmd = commandFor(script, event);
    const list = settings.hooks[event] ?? [];
    const already = list.some((h) =>
      h.hooks.some((x) => x.command === cmd),
    );
    if (already) continue;
    list.push({
      matcher: "*",
      hooks: [{ type: "command", command: cmd, async: true }],
    });
    settings.hooks[event] = list;
  }
  settings[SETTINGS_KEY] = true;
  await fs.writeFile(
    settingsPath,
    JSON.stringify(settings, null, 2) + "\n",
    "utf8",
  );
}

export async function isHooksInstalled(rootPath: string): Promise<boolean> {
  const settingsPath = path.join(rootPath, ".claude", "settings.json");
  try {
    const raw = await fs.readFile(settingsPath, "utf8");
    const settings = JSON.parse(raw) as Settings;
    return settings[SETTINGS_KEY] === true;
  } catch {
    return false;
  }
}
